refact: RAII wrapper for unicorn scope
3Hren/cocaine-core pull request #186
Opened 2017-06-19 16:15 UTC by antmat

Scope is returned by shared_ptr, so we can not rely on dtor to close the scope, this PR provides simple RAII wrapper on shared_ptr on scope

2017-06-19 20:49 UTC, 3Hren requested changes

2017-06-19 20:49 UTC, 3Hren commented on include/cocaine/api/unicorn.hpp
> +    auto_scope_t(unicorn_scope_ptr wrapped) : wrapped(std::move(wrapped)) {}
Mark as explicit.

2017-06-19 20:49 UTC, 3Hren commented on include/cocaine/api/unicorn.hpp
> +    auto_scope_t() = default;
Do you really need default null version?

2017-06-19 20:49 UTC, 3Hren commented on include/cocaine/api/unicorn.hpp
> +            wrapped->close();
Does `close` throw?

2017-06-20 10:45 UTC, antmat commented
explicit ctor do not allow to do smth like
```
auto_scope_t scope = zk.get(....);
...
scope = zk.put(...);
```

2017-06-21 10:24 UTC, 3Hren approved these changes

2017-06-21 10:25 UTC, merged